Adds Guarana soda and Guarana vending machine.
panelass13/tgstation pull request #34
Opened 2020-05-01 20:15 UTC by SrPiwin

## About The Pull Request
Added a new soda called Guarana and a new vending machine with the Guarana theme.
![image](https://user-images.githubusercontent.com/20142642/80838339-344a5800-8bcf-11ea-8163-15e1e7163761.png)
![image](https://user-images.githubusercontent.com/20142642/80838372-45936480-8bcf-11ea-8f36-d48b1d98a964.png)

## Why It's Good For The Game
It's a new soda that players recognize and a new variety of vending machine themed on the soda.

## Changelog
:cl:
add: Added a new soda called Guarana Antarctica
add: Added a Guarana vending machine
/:cl:

2020-05-01 22:05 UTC, Nopm requested changes

2020-05-01 22:05 UTC, Nopm commented on panelastation/code/modules/vending/cola.dm
> +	product_slogans = "Este � o sabor!"
No non-english strings are allowed in the code.

2020-05-01 23:07 UTC, Nopm requested changes

2020-05-01 23:07 UTC, Nopm commented on panelastation/code/modules/vending/cola.dm
> +	desc = "The flavor of Brazil in space!"
Why did you add an entirely new vending machine just for one drink? Remove it.

2020-05-01 23:09 UTC, Nopm commented on panelastation/code/modules/vending/cola.dm
> +	desc = "The flavor of Brazil in space!"
Also fix Travis

2020-05-01 23:10 UTC, SrPiwin commented on panelastation/code/modules/vending/cola.dm
> +	desc = "The flavor of Brazil in space!"
It's not only for a drink, it's just a re-skin of the cola vending machines.

2020-05-01 23:12 UTC, Nopm commented on panelastation/code/modules/vending/cola.dm
> +	desc = "The flavor of Brazil in space!"
It's not a reskin, there is now a completely different vending machine in the code for no good reason.

2020-05-01 23:28 UTC, SrPiwin commented on panelastation/code/modules/vending/cola.dm
> +	desc = "The flavor of Brazil in space!"
Alright

2020-05-02 01:02 UTC, Nopm approved these changes

2020-05-02 01:02 UTC, merged